### ISSUE TITLE
Running construct_data results in error message

### ISSUE THREAD

**Issue by BecketTrotter** [domantasm96/URL-categorization-using-machine-learning#4]
After running 01_construct_features.py this result is returned and it does not appear to create a new dataset.

"None of [Index(['url', 'main_category', 'main_category:confidence'], dtype='object')] are in the [columns]"

**Comment by domantasm96** [comment]
Hey! 

This problem may occur if repository dataset is corrupted(due to GitHub LFS restrictions it seems that uploaded file in repository is corrupted).

Make sure, that you download original dataset from here: [URL categorization dataset file](https://data.world/crowdflower/url-categorization) and declare this dataset path in config.py file in MAIN_DATASET_PATH variable.

It is worth to mention, that I refactored all the code so let me know if this problem still remains unsolved.
