### ISSUE TITLE
Url-Categorization

### ISSUE THREAD

**Issue by rohit-raje-786** [domantasm96/URL-categorization-using-machine-learning#5]
After running the 01_construct_features.py getting an error  "['main_category_confidence'] not in index"

![WhatsApp Image 2021-01-24 at 10 04 24 PM](https://user-images.githubusercontent.com/61861303/105637334-07438100-5e93-11eb-98aa-5ae477c8bc43.jpeg)

**Comment by domantasm96** [comment]
Hey, thank you for your message. 

I think the problem is that URL categorization dataset file is corrupted due to GitHub LFS restrictions. I would suggest you to download an original dataset from https://data.world/crowdflower/url-categorization website.

Let me know if the issue still remains.

**Comment by rohit-raje-786** [comment]
I have downloaded the dataset mentioned in the link below you send and also
set dataset path in config.py file  then too it is showing the error
main_category_index not found.

**Comment by domantasm96** [comment]
Updated code with the fixed solution. The problem was that data.world provides two datasets with the same set of data but with different columns names: 

1) original/URL-categorization-DFE.csv (column: 'main_category:confidence')
2) data/url_categorization_dfe.csv (column: 'main_category_confidence')

In my previous code 2 option dataset was used so if you used 1 option, then the error may occur on different column naming.

Thank you for reporting the problem and let me know if the issue is still remains unsolved or you have any other problems in term of executing this code!

Cheers!

**Comment by rohit-raje-786** [comment]
It worked.
