### ISSUE TITLE
Incorrect category for CNN

### ISSUE THREAD

**Issue by kalpesh-pusalkar** [domantasm96/URL-categorization-using-machine-learning#6]
Hi 

When I try bbc it works.
But when I try this with cnn.com it shows "Business_and_Industry" and "Law_and_Government". Why does it not predict News for CNN.
![image](https://user-images.githubusercontent.com/36398299/108193760-cf4ef700-713b-11eb-9e09-634af6caed9f.png)

Similary i tried https://www.firstpost.com/ and it predicted below
Predicted main category: Law_and_Government
Predicted submain category: People_and_Society

**Comment by domantasm96** [comment]
Hey!

That's the very deep question that has more than one possible answers:

1. CNN home website may contain words that could make an impact for wrong category classification.
2. Most frequent word list could be outdated or need to be improved.

The solution to these answers could be different, but the first thing that comes to my mind is to expand words and get more information about websites as possible. One of the solution may be to not scrape only home website page, but also deeper levels of their content(recursively go to website hyperlinks). That would make more features for website when counting the most frequent words and get weights from it. 

More information may lead to the more accurate model, so it is possible to do recursive scrapping not only for CNN, but for all training set websites then the most frequent models also would be more accurate. That would cost more time, but results of the model could be much better.

However, I did not implemented recursive scrapping since it could be more complex and this project was done for academic research purposes so recursive scrapping implementation needs to be done. Maybe someday when I got more free time, I could try to implement this feature so for now it's in my to-do plan list in the future.

**Comment by domantasm96** [comment]
Current 2020-12-26 words frequency model gets category correctly, but for https://www.firstpost.com/  website it classifies as 'People_and_Society'.

Well, frequency model needs an improvement and if you have a labeled news websites dataset, you could include it in the main dataset.

Also, be sure that websites are not blocking in the scrapping part, because it could affect results negatively with blocking html response text.
